export default [
    {
      id: "fruits1",
      title: "Apples x lb",
      price: 2.1,
      offerPrice: null,
      stock: 12,
      img: "apples.jpg",
      category: "fruits",
    },
    {
      id: "vegetable1",
      title: "bliquam feugiat dui non",
      price: 4.88,
      offerPrice: 3.88,
      stock: 12,
      img: "baby.jpg",
      category: "vegetable",
    },
    {
      id: "vegetable2",
      title: "abciquam feugiat beans",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "beans.jpg",
      category: "vegetable",
    },
    {
      id: "vegetable3",
      title: "Lorem am beans dui non",
      price: 1.88,
      offerPrice: null,
      stock: 12,
      img: "beans2.jpg",
      category: "vegetable",
    },
    {
      id: "fruits2",
      title: "Berry es feugiat mollis",
      price: 2.3,
      offerPrice: null,
      stock: 12,
      img: "berry.jpg",
      category: "fruits",
    },
    {
      id: "fruits3",
      title: "berry feugiat dui non mollis",
      price: 2.22,
      offerPrice: null,
      stock: 12,
      img: "berry2.jpg",
      category: "fruits",
    },
    {
      id: "vegetable4",
      title: "brussels feugiat dui non mollis",
      price: 2.88,
      offerPrice: null,
      stock: 12,
      img: "brussels.jpg",
      category: "vegetable",
    },
    {
      id: "vegetable5",
      title: "carrot feugiat dui non mollis",
      price: 3.88,
      offerPrice: null,
      stock: 12,
      img: "carrot.jpg",
      category: "vegetable",
    },
    {
      id: "vegetable6",
      title: "celery feugiat dui non mollis",
      price: 5.88,
      offerPrice: null,
      stock: 12,
      img: "celery.jpg",
      category: "vegetable",
    },
    {
      id: "fruits4",
      title: "cherry feugiat dui non mollis",
      price: 7.88,
      offerPrice: 6.88,
      stock: 12,
      img: "cherry.jpg",
      category: "fruits",
    },
    {
      id: "meat1",
      title: "chicken feugiat dui non mollis",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "chicken.jpg",
      category: "meat",
    },
    {
      id: "meat2",
      title: "Aliquam feugiat non chicken",
      price: 8.88,
      offerPrice: null,
      stock: 12,
      img: "chicken2.jpg",
      category: "meat",
    },
    {
      id: "fruits5",
      title: "clemen feugiat dui",
      price: 4.99,
      offerPrice: null,
      stock: 12,
      img: "clemen.jpg",
      category: "fruits",
    },
    {
      id: "meat3",
      title: "cod feugiat dui non",
      price: 9.88,
      offerPrice: null,
      stock: 12,
      img: "cod.jpg",
      category: "meat",
    },
    {
      id: "vegetable7",
      title: "corn feugiat non mollis",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "corn.jpg",
      category: "vegetable",
    },
    {
      id: "vegetable8",
      title: "cucumber feugiat dui non",
      price: 4.88,
      offerPrice: 2.5,
      stock: 12,
      img: "cucumber.jpg",
      category: "vegetable",
    },
    {
      id: "fruits6",
      title: "dates feugiat non duilis",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "dates.jpg",
      category: "fruits",
    },
    {
      id: "meat4",
      title: "fresh fish feugiat dui",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "fish.jpg",
      category: "meat",
    },
    {
      id: "meat5",
      title: "fish lorem ipsum",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "fish2.jpg",
      category: "meat",
    },
    {
      id: "meat6",
      title: "fish non mollis feugiat dui",
      price: 4.88,
      offerPrice: 3.25,
      stock: 12,
      img: "fish3.jpg",
      category: "meat",
    },
    {
      id: "fruits7",
      title: "lemon non mollis",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "lemon.jpg",
      category: "fruits",
    },
    {
      id: "fruits8",
      title: "Aliquam lime dui non mollis",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "lime.jpg",
      category: "fruits",
    },
    {
      id: "fruits9",
      title: "Aliquam mango dui non",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "mango.jpg",
      category: "fruits",
    },
    {
      id: "meat7",
      title: "Aliquam meat dui non mollis",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "meat.jpg",
      category: "meat",
    },
    {
      id: "meat8",
      title: "meat feugiat dui non mollis",
      price: 4.88,
      offerPrice: 4.0,
      stock: 12,
      img: "meat2.jpg",
      category: "meat",
    },
    {
      id: "meat9",
      title: "Aliquam feugiat dui non meat",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "meat3.jpg",
      category: "meat",
    },
    {
      id: "vegetable9",
      title: "mix vegetables feugiat dui non mollis",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "mix.jpg",
      category: "vegetable",
    },
    {
      id: "fruits10",
      title: "pears feugiat dui non mollis",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "pears.jpg",
      category: "fruits",
    },
    {
      id: "vegetable10",
      title: "Aliquam pepper dui non mollis",
      price: 4.88,
      offerPrice: 3.99,
      stock: 12,
      img: "pepper.jpg",
      category: "vegetable",
    },
    {
      id: "meat10",
      title: "Aliquam salmon dui non mollis",
      price: 4.88,
      offerPrice: null,
      stock: 12,
      img: "salmon.jpg",
      category: "meat",
    },
  
    {
      id: "bakery1",
      title: "Sprouts Classic Seedsational Bread 14 oz",
      price: 2.25,
      offerPrice: null,
      stock: 12,
      img: "bread.jpg",
      category: "bakery",
    },
    {
      id: "bakery2",
      title: "Traditional Corn Special Bread",
      price: 1.75,
      offerPrice: null,
      stock: 12,
      img: "bread2.jpg",
      category: "bakery",
    },
    {
      id: "bakery3",
      title: "Sprouts Classic Seedsational Bread",
      price: 2.25,
      offerPrice: null,
      stock: 12,
      img: "bread3.jpg",
      category: "bakery",
    },
    {
      id: "bakery4",
      title: "Oven Baked Garlic & Cheese Toast",
      price: 1.7,
      offerPrice: null,
      stock: 12,
      img: "toast.jpg",
      category: "bakery",
    },
    {
      id: "bakery5",
      title: "Oven Baked Italian Herb with Olive Oil Toast",
      price: 2.25,
      offerPrice: null,
      stock: 12,
      img: "toast2.jpg",
      category: "bakery",
    },
    {
      id: "bakery6",
      title: "Raspberry Crumble Cookies",
      price: 2.25,
      offerPrice: null,
      stock: 12,
      img: "cookies.jpg",
      category: "bakery",
    },
    {
      id: "bakery7",
      title: "Chocolate Chip Cookies",
      price: 3.0,
      offerPrice: null,
      stock: 12,
      img: "cookies2.jpg",
      category: "bakery",
    },
    {
      id: "bakery8",
      title: "Freshly Baked Chocolate Chip Cookie",
      price: 2.5,
      offerPrice: null,
      stock: 12,
      img: "cookies3.jpg",
      category: "bakery",
    },
    {
      id: "bakery9",
      title: "Thomas Cinnamon Raisin English Muffins",
      price: 2.25,
      offerPrice: null,
      stock: 12,
      img: "muffin.jpg",
      category: "bakery",
    },
  
    {
      id: "bakery10",
      title: "Mini Zucchini & Carrot Muffin",
      price: 2.25,
      offerPrice: null,
      stock: 12,
      img: "muffin2.jpg",
      category: "bakery",
    },
  
    {
      id: "bakery11",
      title: "Double Chocolate Oat Muffin ",
      price: 2.25,
      offerPrice: null,
      stock: 12,
      img: "muffin3.jpg",
      category: "bakery",
    },
  
    {
      id: "drink1",
      title: "Freshly Brewed Organic Green Tea",
      price: 0.75,
      offerPrice: null,
      stock: 12,
      img: "tea.jpg",
      category: "drink",
    },
  
    {
      id: "drink2",
      title: "Fresh Grinded Frappé coffee",
      price: 1.5,
      offerPrice: null,
      stock: 12,
      img: "coffe.jpg",
      category: "drink",
    },
  
    {
      id: "drink3",
      title: "Caffee Nero Mocha Late",
      price: 1.8,
      offerPrice: null,
      stock: 12,
      img: "coffe2.jpg",
      category: "drink",
    },
  
    {
      id: "drink4",
      title: "Nescafe Clasico Instant Coffee",
      price: 2.2,
      offerPrice: null,
      stock: 12,
      img: "coffe3.jpg",
      category: "drink",
    },
  
    {
      id: "drink5",
      title: "Peet Coffee Decaf Major Dickason Blend",
      price: 2.4,
      offerPrice: 2.1,
      stock: 12,
      img: "coffe4.jpg",
      category: "drink",
    },
  ];
  